### ISSUE TITLE
Common Results

### ISSUE THREAD

**Issue by prabhavgupta** [fossasia/query-server#136]
Add a tab to show 10 results that are common to all the search engines for the stated query.

**Comment by mariobehling** [comment]
Not sure, what you mean. I think it is not necessary.

**Comment by prabhavgupta** [comment]
Like if you search for hello , it will search in all 4 search engines , and give cumulative ranking based on all 4 rankings. And then show results based on rankings.

**Comment by Pk13055** [comment]
Can you close this issue, if no further discussion is necessary, @prabhavgupta

**Comment by AnshulMalik** [comment]
@prabhavgupta wants to say, if we want to give a cumulative result, mixing all search engine's results

That's a feature we can add.

**Comment by shashank-sharma** [comment]
@AnshulMalik According to me this will be a really great feature as it will be much more useful for so many people.

**Comment by bhaveshAn** [comment]
Is this still an issue?

**Comment by AnshulMalik** [comment]
I think so @bhaveshAn, what's your opinion?

**Comment by bhaveshAn** [comment]
Yeah, but what's the point of having common results, how it can be useful. 
Though it seems like we are focusing on some common results, just as if we don't trust the individual search engines' results. 
Since we trust all these engines, then all the results are true.

Apart from this I think we should focus on some result analysis(ALMOST USED BY ALL SEARCH ENGINES), and making visuals for these analysis.

**Comment by AnshulMalik** [comment]
If I were given this API, I would definitely want a aggregated version, since only that would be useful to me(generally speaking). These individual search options may be helpful for for susi but considering other world, the aggregated feature would be really useful.

I didn't get it? Making visuals of analysis?

**Comment by ParthS007** [comment]
@prabhavgupta Please explain more in detail
