### ISSUE TITLE
Python3.x: Making scrapers  Python3 exclusive and adhere to PEP 8 standards

### ISSUE THREAD

**Issue by Pk13055** [fossasia/query-server#151]
Given compatibility issues, all scrapers and the app in general should be ported to Python3.
- [x] Update all functions and modules to Python 3.
- [x] Adhere to PEP 8 styling standards.

**Comment by Pk13055** [comment]
@hpdang Can you please review.

**Comment by cclauss** [comment]
Now that flake8 is set up in Travis, we get __a full listing of all PEP8 style violations__ (the Exxx errors) on each pull request: https://travis-ci.org/fossasia/query-server/jobs/279784188#L662  There is PEP8 cleanup work to do here so I am unsure why there is a checkmark next to __Adhere to PEP 8 styling standards__ above.

**Comment by cclauss** [comment]
Can we either close this issue or rename this issue to "__All Python files should be PEP8 and Flake8 compliant__"?  README.md says that we must support both Python 2 and Python 3 so the current title of this issue is misleading.  PEP8 work is being done in #152, #172, #200 but perhaps the best approach would be for [someone](https://github.com/fossasia/query-server/pull/197#issuecomment-332098383) ( @vaibhavsingh97 ) to run __[autopep8](https://pypi.python.org/pypi/autopep8) --in-place --aggressive --aggressive .__ at the root of the codebase.

**Comment by vaibhavsingh97** [comment]
@cclauss I think I should do it instead of asking from someone to do it 😄. Will send PR 😄

**Comment by cclauss** [comment]
Awesome!!
