### ISSUE TITLE
Incorrect Baidu support

### ISSUE THREAD

**Issue by shashank-sharma** [fossasia/query-server#272]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**

https://query-server.herokuapp.com/api/v1/search/ubaidu?query=fossasia&format=json&num=100
This url is giving application error
**Expected behavior:**
It should give result properly

**Comment by shashank-sharma** [comment]
@bhaveshAn Hey
Again without review your PR was accepted and there are few errors.
1. Again why chinese words are not viewing ? Have you done any check to make sure only english words are accepted.
2. Same results are generating for:
https://www.baidu.com/s?wd=fossasia&pn=11
https://www.baidu.com/s?wd=fossasia&pn=12
https://www.baidu.com/s?wd=fossasia&pn=13
https://www.baidu.com/s?wd=fossasia&pn=14

This is incorrect you might need to change this. Or if anyone else is interested in working on this.

**Comment by bhaveshAn** [comment]
> Same results are generating for:
https://www.baidu.com/s?wd=fossasia&pn=11
https://www.baidu.com/s?wd=fossasia&pn=12
https://www.baidu.com/s?wd=fossasia&pn=13
https://www.baidu.com/s?wd=fossasia&pn=14

This is all because for baidu `pn` is not page index like `start` for google.
`pn` is the index for the resultset. Just like `pn=1` for 1st result and so on. Please, If you wanna check these then do not check like :arrow_up: . Check it from the application there are no duplicate results

> Without review your PR was accepted and there are few errors.

Please refer to https://github.com/fossasia/query-server/pull/230#issuecomment-339110407
Here, I have pinged you too, so to get reviewed and provided heroku deployment https://warm-reaches-23592.herokuapp.com/ 

> Again why chinese words are not viewing ? Have you done any check to make sure only english words are accepted.

Don't know but all the links for baidu search in query-server is working fine and giving the link values same as given by https://www.baidu.com/

Hence, This issue should be closed.

**Comment by shashank-sharma** [comment]
@bhaveshAn 
Why issue should be closed ?
1. Those links are generating from app only. If you will type num to 50 or 100 then you will notice pn will be 11, 12, 13, 14 due to which duplicates are generating. You need to do something for this if possible. See in image
![screenshot from 2017-10-25 19-58-00](https://user-images.githubusercontent.com/9320644/32004232-e726af7c-b9be-11e7-93eb-80fcb136803a.png)


2. In case of chinese search result I am talking about this because so many links are ignored by that. query-search must extract all links available without any exceptions.

3. App is crashing for num = 100
![screenshot from 2017-10-25 19-55-35](https://user-images.githubusercontent.com/9320644/32004048-836b9cc2-b9be-11e7-8a00-d416bc397664.png)
![screenshot from 2017-10-25 19-57-51](https://user-images.githubusercontent.com/9320644/32004202-d8c4b532-b9be-11e7-80d8-91ad30066fcc.png)

It would be great if you can solve these 3 problems
